# Generated by Django 2.2.5 on 2020-10-22 06:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CourseCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_image', models.ImageField(blank=True, null=True, upload_to='video_category/%Y/%m/%d/', verbose_name='Kategoriya Rasmi:')),
                ('category_name', models.CharField(max_length=200, unique=True, verbose_name='Kategoriya Nomi:')),
                ('category_description', models.TextField(verbose_name='Kategoriya Tarifi:')),
            ],
            options={
                'verbose_name': 'Kategoriya:',
                'verbose_name_plural': 'Kategoriyalar:',
            },
        ),
        migrations.CreateModel(
            name='VideoCourse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_url', models.URLField(max_length=300, verbose_name='YouTube Video Linki:')),
                ('video_name', models.TextField(verbose_name='Video Nomi:')),
                ('video_published', models.DateTimeField(auto_now_add=True)),
                ('video_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='video_name', to='video_tutorial.CourseCategory', verbose_name='Video Kategoriyasi:')),
            ],
            options={
                'verbose_name': 'Video:',
                'verbose_name_plural': 'Videolar:',
                'ordering': ['video_published'],
            },
        ),
    ]
