# Generated by Django 2.2.5 on 2020-10-20 06:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProCourseName',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pro_course_image', models.ImageField(blank=True, null=True, upload_to='pro_course/%Y/%m/%d/', verbose_name='Kurs Rasmi:')),
                ('pro_course_name', models.CharField(max_length=200, unique=True, verbose_name='Kurs Nomi:')),
                ('pro_course_description', models.TextField(verbose_name='Kurs Tarifi:')),
            ],
            options={
                'verbose_name': 'Kurs',
                'verbose_name_plural': 'Kurslar',
                'ordering': ['pro_course_name'],
            },
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teacher_name', models.CharField(max_length=200, unique=True, verbose_name="O'qtuvchi Ismi:")),
                ('teacher_info', models.TextField(verbose_name="O'qtuvchi haqida:")),
                ('teacher_image', models.ImageField(blank=True, null=True, upload_to='teacher/', verbose_name='Rasm:')),
            ],
            options={
                'verbose_name': "O'qtuvchi",
                'verbose_name_plural': "O'qtuvchilar",
                'ordering': ['teacher_name'],
            },
        ),
        migrations.CreateModel(
            name='ProCourseInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_coast', models.CharField(blank=True, max_length=200, null=True, verbose_name='Kurs Narxi:')),
                ('course_duration', models.CharField(blank=True, max_length=300, null=True, verbose_name='Kurs Davomiyligi:')),
                ('course_description', models.TextField(verbose_name='Kurs Xaqida:')),
                ('course_published', models.DateTimeField(auto_now_add=True)),
                ('course_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payed_course_name', to='pro_tutorial.ProCourseName', verbose_name='Kurs Nomi:')),
                ('course_teacher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='teacher_course', to='pro_tutorial.Teacher', verbose_name="Kurs O'tuvchisi:")),
            ],
            options={
                'verbose_name': 'Kurs Haqida',
                'verbose_name_plural': 'Kurslar Haqida',
                'ordering': ['course_published'],
            },
        ),
    ]
