# Generated by Django 2.2.5 on 2020-10-16 13:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pro_tutorial', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='procourseinfo',
            name='course_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payed_course_name', to='pro_tutorial.ProCourseName', verbose_name='Kurs Nomi:'),
        ),
    ]
