# Generated by Django 2.2.5 on 2020-11-03 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pro_tutorial', '0003_auto_20201029_1725'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pupil_comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pupil_name', models.CharField(max_length=150, verbose_name="O'quvchi Ismi:")),
                ('join_date', models.DateTimeField(auto_now_add=True, verbose_name='Ariza Sanasi:')),
                ('pupil_image', models.ImageField(blank=True, null=True, upload_to='pupil_image/%Y/%m/%d/', verbose_name="O'quvchi Rasmi:")),
                ('pupil_comment', models.TextField(blank=True, null=True, verbose_name='Izox:')),
                ('pupil_male', models.BooleanField(default=False)),
                ('pupil_female', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name_plural': "O'quvchilar",
                'ordering': ['join_date'],
            },
        ),
    ]
