# Generated by Django 2.2.5 on 2020-11-03 17:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pro_tutorial', '0004_pupil_comment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pupil_comment',
            options={'ordering': ['join_date'], 'verbose_name_plural': 'Izohlar'},
        ),
    ]
