# Generated by Django 2.2.5 on 2020-11-03 17:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pro_tutorial', '0005_auto_20201103_2231'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pupil',
            name='pupil_comment',
        ),
        migrations.RemoveField(
            model_name='pupil',
            name='pupil_female',
        ),
        migrations.RemoveField(
            model_name='pupil',
            name='pupil_image',
        ),
        migrations.RemoveField(
            model_name='pupil',
            name='pupil_male',
        ),
    ]
