# Generated by Django 2.2.5 on 2020-11-03 18:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pro_tutorial', '0006_auto_20201103_2236'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pupil_comment',
            name='pupil_female',
        ),
        migrations.RemoveField(
            model_name='pupil_comment',
            name='pupil_male',
        ),
    ]
