# Generated by Django 2.2.5 on 2020-11-03 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pro_tutorial', '0007_auto_20201103_2337'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pupil_comment',
            name='pupil_comment',
            field=models.TextField(verbose_name='Izox:'),
        ),
    ]
